# MODEL CONFIG
# Data/Audio specifics
annotations_path: '/Users/inigoparra/Desktop/ESC-50-master-2/meta/esc50.csv'
audio_dir: '/Users/inigoparra/Desktop/ESC-50-master-2/audio'
sample_rate: 22050
n_fft: 1024
hop_length: 256
n_mels: 128 # Controls the size

# Train specifics
batch_size: 12
learning_rate: 0.01
validation_split: 0.2
test_split: 0.1
n_epochs: 100
optimizer: 'Adam'
scheduler: 'step'

model_config: 
  img_size: 128
  patch_size: 16
  in_channels: 1
  num_classes: 25
  d_model: 512
  layers: 6
  heads: 4
  h_dim: 1024
  dropout: 0.4

# Wandb logs specifics
wandb_config:
  project: 'speech_cnn_attention_sound_classification'
  config:
    epochs: 100
    batch_size: 12
    learning_rate: 0.01
    optimizer: 'SGD'
    img_size: 256
    patch_size: 16
    in_channels: 3
    num_classes: 25
    d_model: 512
    layers: 12
    heads: 12
    h_dim: 2048
    dropout: 0.2