# MODEL CONFIG
# Seed
seed: 1337

# Data/Audio specifics
num_classes: 10

# Train specifics
batch_size: 8
learning_rate: 0.001
n_epochs: 200
optimizer: 'Adam'
scheduler: 'plateau'
accumulation_steps: 4
grad_clip: True

# Checkpoints
checkpoint_interval: 20

model_config: 
  img_size: 32
  patch_size: 4
  in_channels: 1
  num_classes: 10
  d_model: 512
  layers: 6
  heads: 8
  h_dim: 2048
  dropout: 0.0
  norm_bias: False

# Wandb logs specifics
wandb_config:
  project: 'ViT-Speech-CIFAR10'
  config:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    optimizer: 'Adam'
    img_size: 32
    patch_size: 4
    in_channels: 1
    num_classes: 10
    d_model: 512
    layers: 6
    heads: 8
    h_dim: 2048
    dropout: 0.0