# MODEL CONFIG

# Seed
seed: 1337

# Data/Audio specifics
num_classes: 10
resize: True

# Train specifics
batch_size: 16
learning_rate: 0.001
n_epochs: 50
optimizer: 'Adam'
scheduler: 'plateau'
accumulation_steps: 4
grad_clip: False

# Checkpoints
checkpoints_path: 'model_check'
checkpoint_interval: 20

model_config: 
  img_size: 64
  patch_size: 8
  in_channels: 1
  num_classes: 10
  d_model: 768
  layers: 12
  heads: 12
  h_dim: 3072
  dropout: 0.1
  norm_bias: False

# Wandb logs specifics
wandb_config:
  project: 'ViT-Speech-CIFAR10'
  config:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    optimizer: 'Adam'
    img_size: 64
    patch_size: 8
    in_channels: 1
    num_classes: 10
    d_model: 768
    layers: 12
    heads: 12
    h_dim: 3072
    dropout: 0.1