# MODEL CONFIG
# Seed
seed: 1337

# Dataset
audio_path: /Users/inigoparra/Desktop/ESC-50-master/audio
annotations_path: /Users/inigoparra/Desktop/ESC-50-master/meta/esc50.csv

# Data/Audio specifics
num_classes: 50
n_samples: 22050
sample_rate: 22050
n_fft: 2048
hop_length: 256
n_mels: 256 # spectrogram: n_mels x n_mels
augment: True
n_augment: 5

# Train specifics
batch_size: 16
learning_rate: 0.001
validation_split: 0.2
test_split: 0.1
n_epochs: 100
optimizer: 'Adam'
scheduler: 'plateau'
accumulation_steps: 4
grad_clip: False

# Checkpoints
chekpoints_path: 'model_check'
checkpoint_interval: 20

model_config: 
  img_size: 256
  patch_size: 16
  in_channels: 1
  num_classes: 50
  d_model: 1024
  layers: 24
  heads: 12
  h_dim: 4096
  dropout: 0.1
  norm_bias: False

# Wandb logs specifics
wandb_config:
  project: 'ViT-Speech'
  config:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    optimizer: 'Adam'
    img_size: 256
    patch_size: 16
    in_channels: 1
    num_classes: 50
    d_model: 1024
    layers: 24
    heads: 12
    h_dim: 4096
    dropout: 0.1